-- Backfill cached MCP extension tools discovered before SourceNerve gained its
-- own conservative name-based classification resolver. Future discoveries are
-- classified in Rust before persistence; this migration only repairs existing
-- cached rows during upgrade.
--
-- Mutation signals win over read-looking prefixes. Unknown names remain as-is
-- (NULL/false) so the gateway continues to route them conservatively.

UPDATE mcp_extension_tools
SET
    read_only = 0,
    destructive = CASE
        WHEN lower(original_name) LIKE '%delete%'
          OR lower(original_name) LIKE '%remove%'
          OR lower(original_name) LIKE '%clear%'
          OR lower(original_name) LIKE '%reset%'
          OR lower(original_name) LIKE '%drop%'
          OR lower(original_name) LIKE '%truncate%'
          OR lower(original_name) LIKE '%uninstall%'
        THEN 1
        ELSE destructive
    END
WHERE
       lower(original_name) LIKE '%create%'
    OR lower(original_name) LIKE '%delete%'
    OR lower(original_name) LIKE '%remove%'
    OR lower(original_name) LIKE '%update%'
    OR lower(original_name) LIKE '%write%'
    OR lower(original_name) LIKE '%edit%'
    OR lower(original_name) LIKE '%patch%'
    OR lower(original_name) LIKE '%apply%'
    OR lower(original_name) LIKE '%commit%'
    OR lower(original_name) LIKE '%push%'
    OR lower(original_name) LIKE '%merge%'
    OR lower(original_name) LIKE '%set%'
    OR lower(original_name) LIKE '%add%'
    OR lower(original_name) LIKE '%insert%'
    OR lower(original_name) LIKE '%upsert%'
    OR lower(original_name) LIKE '%ingest%'
    OR lower(original_name) LIKE '%store%'
    OR lower(original_name) LIKE '%save%'
    OR lower(original_name) LIKE '%manage%'
    OR lower(original_name) LIKE '%publish%'
    OR lower(original_name) LIKE '%deploy%'
    OR lower(original_name) LIKE '%execute%'
    OR lower(original_name) LIKE '%import%'
    OR lower(original_name) LIKE '%send%'
    OR lower(original_name) LIKE '%upload%'
    OR lower(original_name) LIKE '%rename%'
    OR lower(original_name) LIKE '%move%'
    OR lower(original_name) LIKE '%copy%'
    OR lower(original_name) LIKE '%clear%'
    OR lower(original_name) LIKE '%reset%'
    OR lower(original_name) LIKE '%drop%'
    OR lower(original_name) LIKE '%truncate%'
    OR lower(original_name) LIKE '%enable%'
    OR lower(original_name) LIKE '%disable%'
    OR lower(original_name) LIKE '%start%'
    OR lower(original_name) LIKE '%stop%'
    OR lower(original_name) LIKE '%restart%'
    OR lower(original_name) LIKE '%approve%'
    OR lower(original_name) LIKE '%revoke%'
    OR lower(original_name) LIKE '%install%'
    OR lower(original_name) LIKE '%uninstall%'
    OR lower(original_name) LIKE '%mutate%'
    OR lower(original_name) LIKE 'refresh%'
    OR lower(original_name) LIKE 'run%'
    OR lower(original_name) LIKE 'sync%'
    OR (
        (lower(original_name) LIKE 'index_%' OR lower(original_name) LIKE 'reindex_%')
        AND lower(original_name) NOT LIKE '%status'
    );

UPDATE mcp_extension_tools
SET
    read_only = 1,
    destructive = 0
WHERE (
       lower(original_name) LIKE 'get_%'
    OR lower(original_name) LIKE 'list_%'
    OR lower(original_name) LIKE 'search_%'
    OR lower(original_name) LIKE 'find_%'
    OR lower(original_name) LIKE 'query_%'
    OR lower(original_name) LIKE 'check_%'
    OR lower(original_name) LIKE 'detect_%'
    OR lower(original_name) LIKE 'trace_%'
    OR lower(original_name) LIKE 'inspect_%'
    OR lower(original_name) LIKE 'describe_%'
    OR lower(original_name) LIKE 'read_%'
    OR lower(original_name) LIKE 'lookup_%'
    OR lower(original_name) LIKE 'fetch_%'
    OR lower(original_name) LIKE 'resolve_%'
    OR lower(original_name) LIKE 'explain_%'
    OR lower(original_name) LIKE 'summarize_%'
    OR lower(original_name) LIKE 'preview_%'
    OR lower(original_name) LIKE 'diff_%'
    OR lower(original_name) LIKE 'status_%'
    OR lower(original_name) LIKE 'show_%'
    OR lower(original_name) LIKE 'view_%'
    OR lower(original_name) LIKE 'count_%'
    OR lower(original_name) LIKE 'calculate_%'
    OR lower(original_name) LIKE 'analyze_%'
    OR lower(original_name) LIKE 'analyse_%'
    OR lower(original_name) LIKE '%_status'
)
AND NOT (
       lower(original_name) LIKE '%create%'
    OR lower(original_name) LIKE '%delete%'
    OR lower(original_name) LIKE '%remove%'
    OR lower(original_name) LIKE '%update%'
    OR lower(original_name) LIKE '%write%'
    OR lower(original_name) LIKE '%edit%'
    OR lower(original_name) LIKE '%patch%'
    OR lower(original_name) LIKE '%apply%'
    OR lower(original_name) LIKE '%commit%'
    OR lower(original_name) LIKE '%push%'
    OR lower(original_name) LIKE '%merge%'
    OR lower(original_name) LIKE '%set%'
    OR lower(original_name) LIKE '%add%'
    OR lower(original_name) LIKE '%insert%'
    OR lower(original_name) LIKE '%upsert%'
    OR lower(original_name) LIKE '%ingest%'
    OR lower(original_name) LIKE '%store%'
    OR lower(original_name) LIKE '%save%'
    OR lower(original_name) LIKE '%manage%'
    OR lower(original_name) LIKE '%publish%'
    OR lower(original_name) LIKE '%deploy%'
    OR lower(original_name) LIKE '%execute%'
    OR lower(original_name) LIKE '%import%'
    OR lower(original_name) LIKE '%send%'
    OR lower(original_name) LIKE '%upload%'
    OR lower(original_name) LIKE '%rename%'
    OR lower(original_name) LIKE '%move%'
    OR lower(original_name) LIKE '%copy%'
    OR lower(original_name) LIKE '%clear%'
    OR lower(original_name) LIKE '%reset%'
    OR lower(original_name) LIKE '%drop%'
    OR lower(original_name) LIKE '%truncate%'
    OR lower(original_name) LIKE '%enable%'
    OR lower(original_name) LIKE '%disable%'
    OR lower(original_name) LIKE '%start%'
    OR lower(original_name) LIKE '%stop%'
    OR lower(original_name) LIKE '%restart%'
    OR lower(original_name) LIKE '%approve%'
    OR lower(original_name) LIKE '%revoke%'
    OR lower(original_name) LIKE '%install%'
    OR lower(original_name) LIKE '%uninstall%'
    OR lower(original_name) LIKE '%mutate%'
);
