import {
  contextBridge,
  ipcRenderer,
  type IpcRendererEvent,
} from "electron";

import {
  DESKTOP_IPC,
  type Auth0SessionView,
  type DaemonHealth,
  type DaemonSnapshot,
  type DesktopBehaviorPreferences,
  type DesktopResult,
  type DesktopRuntimeEvent,
  type DiagnosticsCopyResult,
  type GitProvider,
  type GitTransportValidation,
  type LegacyImportApplyInput,
  type LegacyImportPreview,
  type LegacyImportResult,
  type ManagedWorkspaceView,
  type ProviderAccountView,
  type ProviderRepositorySummary,
  type PublicMcpView,
  type ReadinessPayload,
  type RecoveryActionResult,
  type RecoveryReadinessResult,
  type RecoveryStateView,
  type RuntimeInfo,
  type RuntimeLogEntry,
  type RuntimeLogSnapshot,
  type ServiceStatusPayload,
  type SourceNerveDesktopApi,
  type StateBackupValidationView,
  type SupportBundleExportFormat,
  type SupportBundleExportResult,
  type SupportBundlePreview,
  type WorkspaceIndexResult,
  type WorkspaceRepositorySelection,
  type WorkspaceSaveInput,
  type WorkspaceSummary,
} from "./shared/desktop-api";
import {
  INTELLIGENCE_IPC,
  type IntelligenceArchitectureClusterInput,
  type IntelligenceArchitectureClusterResult,
  type IntelligenceArchitectureMapInput,
  type IntelligenceArchitectureMapResult,
  type IntelligenceArchitectureRebuildResult,
  type IntelligenceCodeSearchResult,
  type IntelligenceContextPack,
  type IntelligenceContextPackInput,
  type IntelligenceFilePreview,
  type IntelligenceGraphStatus,
  type IntelligenceMemorySearchResult,
  type IntelligenceQueryInput,
  type IntelligenceReadFileInput,
  type IntelligenceSemanticSearchInput,
  type IntelligenceSemanticSearchResult,
  type IntelligenceSemanticStatus,
  type IntelligenceSymbolContext,
  type IntelligenceSymbolKeyInput,
  type IntelligenceSymbolSearchInput,
  type IntelligenceSymbolSearchResult,
  type IntelligenceTraceInput,
  type IntelligenceTraceResult,
} from "./shared/intelligence-api";
import {
  MCP_EXTENSION_IPC,
  type McpExtensionApi,
  type McpExtensionApprovalResult,
  type McpExtensionCredentialInput,
  type McpExtensionInstallInput,
  type McpExtensionOAuthActionResult,
  type McpExtensionToolPolicyInput,
  type McpExtensionToolView,
  type McpExtensionView,
  type McpMarketplaceInstallPlan,
  type McpMarketplaceInstallRequest,
  type McpMarketplaceRollbackResult,
  type McpMarketplaceSearchInput,
  type McpMarketplaceServerView,
  type McpMarketplaceUpdateResult,
} from "./shared/mcp-extension-api";
import {
  PLUGIN_VERIFICATION_IPC,
  type PluginCopyResult,
  type PluginDomainChallengeInput,
  type PluginDomainChallengeResult,
  type PluginIconExportResult,
  type PluginOpenResult,
  type PluginVerificationRunResult,
  type PluginVerificationView,
} from "./shared/plugin-verification-api";
import {
  PROVIDER_WORKFLOW_IPC,
  type ProviderDefaultSyncResult,
  type ProviderIssueCreateInput,
  type ProviderIssueCreateResult,
  type ProviderPullCreateInput,
  type ProviderPullCreateResult,
  type ProviderPullMergeInput,
  type ProviderPullMergeResult,
  type ProviderPullRefreshInput,
  type ProviderPullView,
  type ProviderWorkflowState,
} from "./shared/provider-workflow-api";
import {
  TASK_IPC,
  type DesktopTaskApplyInput,
  type DesktopTaskApplyResult,
  type DesktopTaskBeginInput,
  type DesktopTaskBeginResult,
  type DesktopTaskBranchInput,
  type DesktopTaskBranchResult,
  type DesktopTaskCommitInput,
  type DesktopTaskCommitResult,
  type DesktopTaskListItem,
  type DesktopTaskProposalResult,
  type DesktopTaskProposeInput,
  type DesktopTaskPushResult,
  type DesktopTaskReviewResult,
  type DesktopTaskSnapshot,
} from "./shared/task-api";

const api: SourceNerveDesktopApi = {
  getRuntimeInfo: () => ipcRenderer.invoke(DESKTOP_IPC.runtimeInfo) as Promise<DesktopResult<RuntimeInfo>>,
  getDaemonState: () => ipcRenderer.invoke(DESKTOP_IPC.daemonState) as Promise<DesktopResult<DaemonSnapshot>>,
  startDaemon: () => ipcRenderer.invoke(DESKTOP_IPC.daemonStart) as Promise<DesktopResult<DaemonSnapshot>>,
  stopDaemon: () => ipcRenderer.invoke(DESKTOP_IPC.daemonStop) as Promise<DesktopResult<DaemonSnapshot>>,
  restartDaemon: () => ipcRenderer.invoke(DESKTOP_IPC.daemonRestart) as Promise<DesktopResult<DaemonSnapshot>>,
  attachExternalDaemon: () => ipcRenderer.invoke(DESKTOP_IPC.daemonAttachExternal) as Promise<DesktopResult<DaemonSnapshot>>,
  getDaemonHealth: () => ipcRenderer.invoke(DESKTOP_IPC.daemonHealth) as Promise<DesktopResult<DaemonHealth>>,
  getServiceStatus: () => ipcRenderer.invoke(DESKTOP_IPC.serviceStatus) as Promise<DesktopResult<ServiceStatusPayload>>,
  getReadiness: () => ipcRenderer.invoke(DESKTOP_IPC.readiness) as Promise<DesktopResult<ReadinessPayload>>,
  listWorkspaces: () => ipcRenderer.invoke(DESKTOP_IPC.listWorkspaces) as Promise<DesktopResult<WorkspaceSummary[]>>,
  pickWorkspaceRepository: () => ipcRenderer.invoke(DESKTOP_IPC.workspacePickRepository) as Promise<DesktopResult<WorkspaceRepositorySelection | null>>,
  listManagedWorkspaces: () => ipcRenderer.invoke(DESKTOP_IPC.workspaceListManaged) as Promise<DesktopResult<ManagedWorkspaceView[]>>,
  saveWorkspace: (input: WorkspaceSaveInput) => ipcRenderer.invoke(DESKTOP_IPC.workspaceSave, input) as Promise<DesktopResult<ManagedWorkspaceView>>,
  removeWorkspace: (workspaceId: string) => ipcRenderer.invoke(DESKTOP_IPC.workspaceRemove, workspaceId) as Promise<DesktopResult<{ removed: boolean }>>,
  indexWorkspace: (workspaceId: string) => ipcRenderer.invoke(DESKTOP_IPC.workspaceIndex, workspaceId) as Promise<DesktopResult<WorkspaceIndexResult>>,
  pickLegacyImport: () => ipcRenderer.invoke(DESKTOP_IPC.legacyImportPick) as Promise<DesktopResult<LegacyImportPreview | null>>,
  applyLegacyImport: (input: LegacyImportApplyInput) => ipcRenderer.invoke(DESKTOP_IPC.legacyImportApply, input) as Promise<DesktopResult<LegacyImportResult>>,
  getAuth0State: () => ipcRenderer.invoke(DESKTOP_IPC.auth0State) as Promise<DesktopResult<Auth0SessionView>>,
  signInAuth0: () => ipcRenderer.invoke(DESKTOP_IPC.auth0SignIn) as Promise<DesktopResult<Auth0SessionView>>,
  refreshAuth0: () => ipcRenderer.invoke(DESKTOP_IPC.auth0Refresh) as Promise<DesktopResult<Auth0SessionView>>,
  logoutAuth0: () => ipcRenderer.invoke(DESKTOP_IPC.auth0Logout) as Promise<DesktopResult<Auth0SessionView>>,
  getProviderStates: () => ipcRenderer.invoke(DESKTOP_IPC.providerStates) as Promise<DesktopResult<ProviderAccountView[]>>,
  connectProvider: (provider: GitProvider) => ipcRenderer.invoke(DESKTOP_IPC.providerConnect, provider) as Promise<DesktopResult<ProviderAccountView>>,
  disconnectProvider: (provider: GitProvider) => ipcRenderer.invoke(DESKTOP_IPC.providerDisconnect, provider) as Promise<DesktopResult<ProviderAccountView>>,
  listProviderRepositories: (provider: GitProvider) => ipcRenderer.invoke(DESKTOP_IPC.providerRepositories, provider) as Promise<DesktopResult<ProviderRepositorySummary[]>>,
  validateProviderRepository: (provider: GitProvider, repository: string) => ipcRenderer.invoke(DESKTOP_IPC.providerValidateRepository, provider, repository) as Promise<DesktopResult<ProviderRepositorySummary>>,
  validateGitTransport: (workspaceId: string) => ipcRenderer.invoke(DESKTOP_IPC.providerValidateTransport, workspaceId) as Promise<DesktopResult<GitTransportValidation>>,
  getPublicMcpState: () => ipcRenderer.invoke(DESKTOP_IPC.publicMcpState) as Promise<DesktopResult<PublicMcpView>>,
  enrollPublicMcp: () => ipcRenderer.invoke(DESKTOP_IPC.publicMcpEnroll) as Promise<DesktopResult<PublicMcpView>>,
  retryPublicMcp: () => ipcRenderer.invoke(DESKTOP_IPC.publicMcpRetry) as Promise<DesktopResult<PublicMcpView>>,
  rotatePublicMcpCredential: () => ipcRenderer.invoke(DESKTOP_IPC.publicMcpRotate) as Promise<DesktopResult<PublicMcpView>>,
  revokePublicMcp: () => ipcRenderer.invoke(DESKTOP_IPC.publicMcpRevoke) as Promise<DesktopResult<PublicMcpView>>,
  reEnrollPublicMcp: () => ipcRenderer.invoke(DESKTOP_IPC.publicMcpReEnroll) as Promise<DesktopResult<PublicMcpView>>,
  getRuntimeLogs: () => ipcRenderer.invoke(DESKTOP_IPC.runtimeLogs) as Promise<DesktopResult<RuntimeLogSnapshot>>,
  copyDiagnostics: () => ipcRenderer.invoke(DESKTOP_IPC.diagnosticsCopy) as Promise<DesktopResult<DiagnosticsCopyResult>>,
  previewSupportBundle: () => ipcRenderer.invoke(DESKTOP_IPC.supportBundlePreview) as Promise<DesktopResult<SupportBundlePreview>>,
  exportSupportBundle: (selectionId: string, format: SupportBundleExportFormat) => ipcRenderer.invoke(DESKTOP_IPC.supportBundleExport, selectionId, format) as Promise<DesktopResult<SupportBundleExportResult>>,
  getRecoveryState: () => ipcRenderer.invoke(DESKTOP_IPC.recoveryState) as Promise<DesktopResult<RecoveryStateView>>,
  rebuildManagedIndexes: () => ipcRenderer.invoke(DESKTOP_IPC.recoveryRebuildIndexes) as Promise<DesktopResult<RecoveryActionResult>>,
  createAndValidateStateBackup: () => ipcRenderer.invoke(DESKTOP_IPC.recoveryBackupCreateValidate) as Promise<DesktopResult<StateBackupValidationView>>,
  validateLatestStateBackup: () => ipcRenderer.invoke(DESKTOP_IPC.recoveryBackupValidateLatest) as Promise<DesktopResult<StateBackupValidationView>>,
  openStateDirectory: () => ipcRenderer.invoke(DESKTOP_IPC.recoveryOpenStateDirectory) as Promise<DesktopResult<{ opened: true }>>,
  openLogsDirectory: () => ipcRenderer.invoke(DESKTOP_IPC.recoveryOpenLogsDirectory) as Promise<DesktopResult<{ opened: true }>>,
  resetDesktopUiSettings: () => ipcRenderer.invoke(DESKTOP_IPC.recoveryResetUiSettings) as Promise<DesktopResult<RecoveryActionResult>>,
  rerunRecoveryReadiness: () => ipcRenderer.invoke(DESKTOP_IPC.recoveryReadiness) as Promise<DesktopResult<RecoveryReadinessResult>>,
  getDesktopBehavior: () => ipcRenderer.invoke(DESKTOP_IPC.desktopBehavior) as Promise<DesktopResult<DesktopBehaviorPreferences>>,
  updateDesktopBehavior: (preferences: DesktopBehaviorPreferences) => ipcRenderer.invoke(DESKTOP_IPC.desktopBehaviorUpdate, preferences) as Promise<DesktopResult<DesktopBehaviorPreferences>>,
  getIntelligenceGraphStatus: (workspace: string) => ipcRenderer.invoke(INTELLIGENCE_IPC.graphStatus, workspace) as Promise<DesktopResult<IntelligenceGraphStatus>>,
  searchIntelligenceMemory: (input: IntelligenceQueryInput) => ipcRenderer.invoke(INTELLIGENCE_IPC.memorySearch, input) as Promise<DesktopResult<IntelligenceMemorySearchResult>>,
  searchIntelligenceCode: (input: IntelligenceQueryInput) => ipcRenderer.invoke(INTELLIGENCE_IPC.codeSearch, input) as Promise<DesktopResult<IntelligenceCodeSearchResult>>,
  searchIntelligenceSymbols: (input: IntelligenceSymbolSearchInput) => ipcRenderer.invoke(INTELLIGENCE_IPC.symbolSearch, input) as Promise<DesktopResult<IntelligenceSymbolSearchResult>>,
  getIntelligenceSymbolContext: (input: IntelligenceSymbolKeyInput) => ipcRenderer.invoke(INTELLIGENCE_IPC.symbolContext, input) as Promise<DesktopResult<IntelligenceSymbolContext>>,
  traceIntelligence: (input: IntelligenceTraceInput) => ipcRenderer.invoke(INTELLIGENCE_IPC.trace, input) as Promise<DesktopResult<IntelligenceTraceResult>>,
  getIntelligenceArchitectureMap: (input: IntelligenceArchitectureMapInput) => ipcRenderer.invoke(INTELLIGENCE_IPC.architectureMap, input) as Promise<DesktopResult<IntelligenceArchitectureMapResult>>,
  getIntelligenceArchitectureCluster: (input: IntelligenceArchitectureClusterInput) => ipcRenderer.invoke(INTELLIGENCE_IPC.architectureCluster, input) as Promise<DesktopResult<IntelligenceArchitectureClusterResult>>,
  rebuildIntelligenceArchitecture: (workspace: string) => ipcRenderer.invoke(INTELLIGENCE_IPC.architectureRebuild, workspace) as Promise<DesktopResult<IntelligenceArchitectureRebuildResult>>,
  buildIntelligenceContextPack: (input: IntelligenceContextPackInput) => ipcRenderer.invoke(INTELLIGENCE_IPC.contextPack, input) as Promise<DesktopResult<IntelligenceContextPack>>,
  getIntelligenceSemanticStatus: (workspace: string) => ipcRenderer.invoke(INTELLIGENCE_IPC.semanticStatus, workspace) as Promise<DesktopResult<IntelligenceSemanticStatus>>,
  searchIntelligenceSemantic: (input: IntelligenceSemanticSearchInput) => ipcRenderer.invoke(INTELLIGENCE_IPC.semanticSearch, input) as Promise<DesktopResult<IntelligenceSemanticSearchResult>>,
  readIntelligenceFile: (input: IntelligenceReadFileInput) => ipcRenderer.invoke(INTELLIGENCE_IPC.readFile, input) as Promise<DesktopResult<IntelligenceFilePreview>>,
  listDesktopTasks: () => ipcRenderer.invoke(TASK_IPC.list) as Promise<DesktopResult<DesktopTaskListItem[]>>,
  beginDesktopTask: (input: DesktopTaskBeginInput) => ipcRenderer.invoke(TASK_IPC.begin, input) as Promise<DesktopResult<DesktopTaskBeginResult>>,
  rememberDesktopTask: (taskId: string) => ipcRenderer.invoke(TASK_IPC.remember, taskId) as Promise<DesktopResult<DesktopTaskSnapshot>>,
  getDesktopTask: (taskId: string) => ipcRenderer.invoke(TASK_IPC.get, taskId) as Promise<DesktopResult<DesktopTaskSnapshot>>,
  cancelDesktopTask: (taskId: string) => ipcRenderer.invoke(TASK_IPC.cancel, taskId) as Promise<DesktopResult<DesktopTaskSnapshot>>,
  checkoutDesktopTaskBranch: (input: DesktopTaskBranchInput) => ipcRenderer.invoke(TASK_IPC.branch, input) as Promise<DesktopResult<DesktopTaskBranchResult>>,
  proposeDesktopTaskPatch: (input: DesktopTaskProposeInput) => ipcRenderer.invoke(TASK_IPC.propose, input) as Promise<DesktopResult<DesktopTaskProposalResult>>,
  applyDesktopTaskProposal: (input: DesktopTaskApplyInput) => ipcRenderer.invoke(TASK_IPC.apply, input) as Promise<DesktopResult<DesktopTaskApplyResult>>,
  reviewDesktopTask: (taskId: string) => ipcRenderer.invoke(TASK_IPC.review, taskId) as Promise<DesktopResult<DesktopTaskReviewResult>>,
  commitDesktopTask: (input: DesktopTaskCommitInput) => ipcRenderer.invoke(TASK_IPC.commit, input) as Promise<DesktopResult<DesktopTaskCommitResult>>,
  pushDesktopTask: (taskId: string) => ipcRenderer.invoke(TASK_IPC.push, taskId) as Promise<DesktopResult<DesktopTaskPushResult>>,
  getPluginVerificationState: () => ipcRenderer.invoke(PLUGIN_VERIFICATION_IPC.state) as Promise<DesktopResult<PluginVerificationView>>,
  verifyPluginConnection: () => ipcRenderer.invoke(PLUGIN_VERIFICATION_IPC.verify) as Promise<DesktopResult<PluginVerificationRunResult>>,
  copyPluginSetupFields: () => ipcRenderer.invoke(PLUGIN_VERIFICATION_IPC.copyFields) as Promise<DesktopResult<PluginCopyResult>>,
  openChatGptPluginSetup: () => ipcRenderer.invoke(PLUGIN_VERIFICATION_IPC.openChatGpt) as Promise<DesktopResult<PluginOpenResult>>,
  exportPluginIcon: () => ipcRenderer.invoke(PLUGIN_VERIFICATION_IPC.exportIcon) as Promise<DesktopResult<PluginIconExportResult>>,
  setPluginDomainChallenge: (input: PluginDomainChallengeInput) => ipcRenderer.invoke(PLUGIN_VERIFICATION_IPC.challengeSet, input) as Promise<DesktopResult<PluginDomainChallengeResult>>,
  verifyPluginDomainChallenge: () => ipcRenderer.invoke(PLUGIN_VERIFICATION_IPC.challengeVerify) as Promise<DesktopResult<PluginDomainChallengeResult>>,
  removePluginDomainChallenge: () => ipcRenderer.invoke(PLUGIN_VERIFICATION_IPC.challengeRemove) as Promise<DesktopResult<PluginDomainChallengeResult>>,
  getProviderWorkflowState: (taskId: string) => ipcRenderer.invoke(PROVIDER_WORKFLOW_IPC.state, taskId) as Promise<DesktopResult<ProviderWorkflowState>>,
  createProviderIssue: (input: ProviderIssueCreateInput) => ipcRenderer.invoke(PROVIDER_WORKFLOW_IPC.issueCreate, input) as Promise<DesktopResult<ProviderIssueCreateResult>>,
  createProviderPull: (input: ProviderPullCreateInput) => ipcRenderer.invoke(PROVIDER_WORKFLOW_IPC.pullCreate, input) as Promise<DesktopResult<ProviderPullCreateResult>>,
  refreshProviderPull: (input: ProviderPullRefreshInput) => ipcRenderer.invoke(PROVIDER_WORKFLOW_IPC.pullRefresh, input) as Promise<DesktopResult<ProviderPullView>>,
  mergeProviderPull: (input: ProviderPullMergeInput) => ipcRenderer.invoke(PROVIDER_WORKFLOW_IPC.pullMerge, input) as Promise<DesktopResult<ProviderPullMergeResult>>,
  syncProviderDefaultBranch: (taskId: string) => ipcRenderer.invoke(PROVIDER_WORKFLOW_IPC.defaultSync, taskId) as Promise<DesktopResult<ProviderDefaultSyncResult>>,
  cancelOperation: (operationId: string) => ipcRenderer.invoke(DESKTOP_IPC.cancelOperation, operationId) as Promise<DesktopResult<{ cancelled: boolean }>>,
  subscribeRuntimeEvents(listener: (event: DesktopRuntimeEvent) => void): () => void {
    const handler = (_event: IpcRendererEvent, payload: DesktopRuntimeEvent) => listener(payload);
    ipcRenderer.on(DESKTOP_IPC.runtimeEvent, handler);
    return () => ipcRenderer.removeListener(DESKTOP_IPC.runtimeEvent, handler);
  },
  subscribeRuntimeLogs(listener: (entry: RuntimeLogEntry) => void): () => void {
    const handler = (_event: IpcRendererEvent, payload: RuntimeLogEntry) => listener(payload);
    ipcRenderer.on(DESKTOP_IPC.runtimeLogEvent, handler);
    return () => ipcRenderer.removeListener(DESKTOP_IPC.runtimeLogEvent, handler);
  },
};

const extensionApi: McpExtensionApi = {
  list: () => ipcRenderer.invoke(MCP_EXTENSION_IPC.list) as Promise<DesktopResult<McpExtensionView[]>>,
  install: (input: McpExtensionInstallInput) => ipcRenderer.invoke(MCP_EXTENSION_IPC.install, input) as Promise<DesktopResult<McpExtensionView>>,
  enable: (extensionId: string) => ipcRenderer.invoke(MCP_EXTENSION_IPC.enable, extensionId) as Promise<DesktopResult<McpExtensionView>>,
  disable: (extensionId: string) => ipcRenderer.invoke(MCP_EXTENSION_IPC.disable, extensionId) as Promise<DesktopResult<McpExtensionView>>,
  restart: (extensionId: string) => ipcRenderer.invoke(MCP_EXTENSION_IPC.restart, extensionId) as Promise<DesktopResult<McpExtensionToolView[]>>,
  remove: (extensionId: string) => ipcRenderer.invoke(MCP_EXTENSION_IPC.remove, extensionId) as Promise<DesktopResult<{ removed: boolean }>>,
  listTools: (extensionId: string) => ipcRenderer.invoke(MCP_EXTENSION_IPC.tools, extensionId) as Promise<DesktopResult<McpExtensionToolView[]>>,
  updateToolPolicy: (input: McpExtensionToolPolicyInput) => ipcRenderer.invoke(MCP_EXTENSION_IPC.toolPolicy, input) as Promise<DesktopResult<McpExtensionToolView>>,
  setCredential: (input: McpExtensionCredentialInput) => ipcRenderer.invoke(MCP_EXTENSION_IPC.credentialSet, input) as Promise<DesktopResult<{ configured: true }>>,
  clearCredential: (extensionId: string) => ipcRenderer.invoke(MCP_EXTENSION_IPC.credentialClear, extensionId) as Promise<DesktopResult<{ configured: false }>>,
  approveNext: (publicTool: string) => ipcRenderer.invoke(MCP_EXTENSION_IPC.approveNext, publicTool) as Promise<DesktopResult<McpExtensionApprovalResult>>,
  connectOAuth: (extensionId: string) => ipcRenderer.invoke(MCP_EXTENSION_IPC.oauthConnect, extensionId) as Promise<DesktopResult<McpExtensionOAuthActionResult>>,
  refreshOAuth: (extensionId: string) => ipcRenderer.invoke(MCP_EXTENSION_IPC.oauthRefresh, extensionId) as Promise<DesktopResult<McpExtensionOAuthActionResult>>,
  revokeOAuth: (extensionId: string) => ipcRenderer.invoke(MCP_EXTENSION_IPC.oauthRevoke, extensionId) as Promise<DesktopResult<McpExtensionOAuthActionResult>>,
  searchMarketplace: (input: McpMarketplaceSearchInput) => ipcRenderer.invoke(MCP_EXTENSION_IPC.marketplaceSearch, input) as Promise<DesktopResult<McpMarketplaceServerView[]>>,
  planMarketplaceInstall: (serverName: string) => ipcRenderer.invoke(MCP_EXTENSION_IPC.marketplacePlan, serverName) as Promise<DesktopResult<McpMarketplaceInstallPlan>>,
  installMarketplace: (input: McpMarketplaceInstallRequest) => ipcRenderer.invoke(MCP_EXTENSION_IPC.marketplaceInstall, input) as Promise<DesktopResult<McpExtensionView>>,
  updateMarketplace: (extensionId: string) => ipcRenderer.invoke(MCP_EXTENSION_IPC.marketplaceUpdate, extensionId) as Promise<DesktopResult<McpMarketplaceUpdateResult>>,
  rollbackMarketplace: (extensionId: string) => ipcRenderer.invoke(MCP_EXTENSION_IPC.marketplaceRollback, extensionId) as Promise<DesktopResult<McpMarketplaceRollbackResult>>,
};

contextBridge.exposeInMainWorld("sourcenerveDesktop", api);
contextBridge.exposeInMainWorld("sourcenerveMcpExtensions", extensionApi);
